### ISSUE TITLE
Add github badge in the website to redirect to this repository

### ISSUE THREAD

**Issue by stephin007** [stephin007/biteAdvisor-FE#10]

**Comment by giri-madhan** [comment]
Hi, @stephin007! I'm interested in working on this issue. Can I add a GitHub badge at the bottom of the page? I would appreciate it if you could share your ideas and suggestions regarding the desired appearance of the badge. Thank you!

**Comment by stephin007** [comment]
@giri-madhan I hope you have seen the website, what do you think is the best position to add the github badge?

**Comment by stephin007** [comment]
@giri-madhan I was referring to where are you planning to place the badge? in the navbar or anywhere else?

color design , etc can obvously be changed.

**Comment by giri-madhan** [comment]
I think placing the badge at the bottom of the page would be a suitable option. What are your thoughts on this?

**Comment by stephin007** [comment]
@giri-madhan at the bottom as in the footer u mean?

**Comment by giri-madhan** [comment]
Oops, I thought I had posted the screenshot of the implementation. This is what I meant. I already have a prototype code ready.
<img width="491" alt="Screenshot 2023-05-29 at 11 00 18 PM" src="https://github.com/stephin007/biteAdvisor-FE/assets/87971509/3c9dae2c-1b6d-4241-9e50-6948db9d8a38">

**Comment by stephin007** [comment]
It doesn't look good there! 🥲 @giri-madhan 

Can you add a diagonal fork on github ribbon at the top to the right side of navbar?  

Like shown here : https://simonwhitaker.github.io/github-fork-ribbon-css/

Infact you can use the CDN in the above link, to implement the same

**Comment by giri-madhan** [comment]
You mean like this one @stephin007 ? 
<img width="1280" alt="Screenshot 2023-05-29 at 11 15 56 PM" src="https://github.com/stephin007/biteAdvisor-FE/assets/87971509/bb22eecb-8386-4b70-9a20-2812edcbcabf">

**Comment by stephin007** [comment]
Hows it looking in mobile view?

**Comment by giri-madhan** [comment]
<img width="361" alt="Screenshot 2023-05-29 at 11 30 39 PM" src="https://github.com/stephin007/biteAdvisor-FE/assets/87971509/a32b364e-7286-44bc-97aa-673c9d5a8702">

This is how it looks on mobile @stephin007 . Is this okay?

**Comment by stephin007** [comment]
Umm, not really ! The app is mobile specific, this ribbon looks good in desktop but not in the mobile view.


Lets do this, can you add a github symbol in the navbar to the right side of the name of the app.

You can use the github icon logo from the boxicon website, whose cdn is already added in the `index.html`

**Comment by giri-madhan** [comment]
Hi @stephin007 , Could you please provide your feedback for this? 
<img width="347" alt="Screenshot 2023-05-30 at 12 03 56 AM" src="https://github.com/stephin007/biteAdvisor-FE/assets/87971509/e3c04d8e-5a0a-428c-9708-d5bdd9d9c451">

**Comment by stephin007** [comment]
@giri-madhan looks good, but i guess i need to see the preview to comment better. Please raise a PR according to the contributing.md file.

**Comment by giri-madhan** [comment]
Hi @stephin007, I have added the PR #15. Could you take a look into it and share what you think? Thanks.

**Comment by stephin007** [comment]
Left a comment @giri-madhan please check

**Comment by giri-madhan** [comment]
Sure @stephin007. I have made the changes requested in the PR now.

**Comment by stephin007** [comment]
This is implemented here #15
